### PR TITLE
Add target_iscsi_portal to manage iscsi portals

### PR DESCRIPTION
**Pull request by psykotox**
Hello!

Thank you for your ansible modules to manage an iSCSI target.
I needed on my side to manage portals to make a target accessible only on certain IPs of my server.
I based myself on your modules to write a new one to manage these portals.
I offer you my module to complete yours :)

Have you ever thought/attempted to do a PR on the official ansible repo with your modules ?

Regards,

Loïc

### CODE REVIEW

**Comment by OndrejHome** [comment]
Hi Loïc,
Thank you for using the modules and taking interest in extending them with new functionality!
I will have a look more in detail on the portal module, test and give you feedback if there are any changes needed before it can be merged. I will have look at this during upcoming weekend or next week. Thank you for your patience.

> Have you ever thought/attempted to do a PR on the official ansible repo with your modules ?

I have thought about it, but never attempted :) One of the requirements that I have seen for official inclusion of modules are functional (automated) test, which is area where my modules are lacking - I test them mostly by hand. 
Even though the modules are not part of official ansible distribution, they can be easily added via ansible galaxy `ansible-galaxy install ondrejhome.targetcli-modules`. Out of curiosity: How have you found these modules and started using them? (github/ansible galaxy/other way)

**Comment by psykotox** [comment]
Hi Ondrej,
I found this module just with a google request : `ansible targetcli` ;) 
And after I show this module and the associated role on the ansible galaxy.

**Comment by OndrejHome** [comment]
Hi Loïc,
Thank you for response and your patience. I have tested the code in my test environment and it works well for me, so shortly I will merge it. There was only one non-technical thing that I will fix myself after merge (renaming 'LUN' to 'portal' in comments for consistency).

Once again Thank you for proposing the change and submitting this PR.

**Comment by OndrejHome** [comment]
Merged, updated and tagged as `3.0.0`. You can now also see the new version `3.0.0` on Ansible Galaxy. Thank you for contribution @psykotox !

**Pull request merged**
